collections:
  authors:
    output: true

baseurl: /

plugins:
  - jekyll-datapage-generator

defaults:
  - scope:
      path: ''
      type: 'authors'
    values:
      layout: 'author'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
    values:
      layout: 'default'

page_gen-dirs: false # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'fatwas.history.title'
    template: 'fatwa-post'
    name: 'name'
    dir: 'fatwas/history'
  - data: 'fatwas.beliefs.title'
    template: 'fatwa-post'
    name: 'webpage'
    dir: 'fatwas/beliefs'
